### ISSUE TITLE
Fitur Laporan.

### ISSUE THREAD

**Issue by lasida** [agunggnw/lasida#1]
FItur Laporan dibuat 2 aja gung
- Laporan Tagihan
  - bisa dicetak
  - Filter by
    - dari tahun
    - dari bulan
    - sampai tahun
    - sampai bulan
    - no  #pelanggan
- Laporan Pelanggan
  - bisa dicetak
  - filter by kecamatan sama kelurahan

**Comment by agunggnw** [comment]
jis kan kelurahan katanya gak dipake

**Comment by lasida** [comment]
yang gak dipake yang kabupaten gung, kelurahan tetep dipake kata orangnya gung

**Comment by lasida** [comment]
Yang nampilin laporan by Tahun awal - akhir belum, bisa keluar, sama kalo di print, dibuat open new tab aja gung

**Comment by agunggnw** [comment]
tes jis, paling tinggal rapihin output laporan

**Comment by lasida** [comment]
wokray
