### ISSUE TITLE
Fitur Administrator

### ISSUE THREAD

**Issue by lasida** [agunggnw/lasida#3]
- dibuat bisa crud aja gung, biar bisa multi user

**Comment by LembagaX** [comment]
role nya apa aja? sama halaman mana yang bisa di akses tiap role nya

**Comment by agunggnw** [comment]
role nya apa aja? sama halaman mana yang bisa di akses tiap role nya

**Comment by lasida** [comment]
rolenya, administrator, sama staff aja, kalo staff nggak bisa ngubah konfigurasi permeter
