### ISSUE TITLE
Fitur Master & Konfigurasi

### ISSUE THREAD

**Issue by lasida** [agunggnw/lasida#4]
- dibuat CRUD aja gung yang kecamatan, sama kelurahan.

**Comment by lasida** [comment]
ada bug di halaman konfigurasi.php 

>  Unable to jump to row 0 on MySQL result index 18

@agunggnw

**Comment by lasida** [comment]
Tinggal yang error ini doang gung, bagian di konfigurasi masih belom fix @agunggnw

**Comment by agunggnw** [comment]
Test
